ALTER TABLE submission ADD COLUMN deleted BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE e621 ADD COLUMN deleted BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE weasyl ADD COLUMN deleted BOOLEAN NOT NULL DEFAULT false;
